export const plans = [
  {
    title: "cheese cake",
    desc: "Each Friday we deliver highest discounts",
    author: "Chef Deming",
    date: "30 min ago",
    location: "S.Korea, Daegu",
    img: "/products/cheese-cake-02.jpg",
  },
  {
    title: "Coming Soon",
    desc: "Be ready for fresh Arrivals from Monday!",
    author: "Belissimo Arthur",
    date: "2 days ago",
    location: "Turkey, Istambul",
    img: "/products/Choco-cake-02.jpeg",
  },
  {
    title: "New Project Lunch",
    desc: "New Restaurant is opening in Florida",
    author: "Morgan News",
    date: "5 days ago",
    location: "USA, Florida",
    img: "/products/cup-cake-02.jpg",
  },
  {
    title: "Join us on sns",
    desc: "🥬 We are offering healthy food reciepies on sns",
    author: "Belissimo Agent",
    date: "A week ago",
    location: "Europe, France",
    img: "/products/Fresh-cake-02.jpg",
  },
  {
    title: "Hot Discount Days",
    desc: "Each Friday we deliver highest discounts",
    author: "Chef Deming",
    date: "30 min ago",
    location: "S.Korea, Daegu",
    img: "/products/Napalyon-cake-02.jpg",
  },
  {
    title: "Coming Soon",
    desc: "Be ready for fresh Arrivals from Monday!",
    author: "Belissimo Arthur",
    date: "2 days ago",
    location: "Turkey, Istambul",
    img: "/products/role-cake-02.jpg",
  },
  {
    title: "New Project Lunch",
    desc: "New Restaurant is opening in Florida",
    author: "Morgan News",
    date: "5 days ago",
    location: "USA, Florida",
    img: "/products/White-cake-02.jpg",
  },
  {
    title: "Join us on sns",
    desc: "🥬 We are offering healthy food reciepies on sns",
    author: "Belissimo Agent",
    date: "A week ago",
    location: "Europe, France",
    img: "/products/Snickers-cake-02.jpeg",
  },
];
