export const plans = [
  {
    title: "Cheese cake",
    desc: "delicious cheesecake",
    author: "Chef Deming",
    date: "order first",
    location: "S.Korea, Daegu",
    img: "/products/cheese-cake-02.jpg",
  },
  {
    title: "Choko cake",
    desc: "delicious chocolate cake",
    author: "Belissimo Arthur",
    date: "order first",
    location: "S.Korea, Daegu",
    img: "/products/Choco-cake-02.jpeg",
  },
  {
    title: "Cup cake",
    desc: "chocolate cup cake",
    author: "Morgan News",
    date: "order first",
    location: "S.Korea, Seoul",
    img: "/products/cup-cake-02.jpg",
  },
  {
    title: "Fresh cake",
    desc: "Cake with 5 different fruits",
    author: "Belissimo Agent",
    date: "order first",
    location: "S.Korea, Busan",
    img: "/products/Fresh-cake-02.jpg",
  },
  {
    title: "Nopolyon",
    desc: " With a layer of crusty dough",
    author: "Chef Deming",
    date: "available",
    location: "S.Korea, Busan",
    img: "/products/Napalyon-cake-02.jpg",
  },
  {
    title: "Role cake",
    desc: "between four creamy wrappers!",
    author: "Belissimo Arthur",
    date: "order first",
    location: "S.Korea, Daejon",
    img: "/products/role-cake-02.jpg",
  },
  {
    title: "White cake",
    desc: "cream wedding cake",
    author: "Morgan News",
    date: "available",
    location: "S.Korea, Daejon",
    img: "/products/White-cake-02.jpg",
  },
  {
    title: "Snickers cake",
    desc: "Coming soon",
    author: "Belissimo Agent",
    date: "coming soon",
    location: "S.Korea, Seoul",
    img: "/products/Snickers-cake-03.jpeg",
  },
];
